# Generated by Django 3.1.6 on 2021-03-02 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210224_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_born',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 10, 55, 4, 497434, tzinfo=utc)),
        ),
    ]
