# Generated by Django 3.1.6 on 2021-03-02 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_date_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 10, 57, 21, 662249, tzinfo=utc), verbose_name='Дата смены статуса'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_born',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 10, 57, 21, 662208, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
