# Generated by Django 3.1.6 on 2021-03-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210302_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_born',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата смены статуса'),
        ),
    ]
