# Generated by Django 3.1.6 on 2021-02-12 21:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Дружественный URL')),
                ('meta_title', models.TextField(blank=True, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('preview_image', models.FileField(upload_to='preview')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('content_one', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый блок первый')),
                ('content_two', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый блок второй')),
                ('content_three', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый блок третий')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницу',
            },
            bases=('pages.basepage',),
        ),
    ]
