# Generated by Django 3.1.6 on 2021-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграмм'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='vk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вконтакте'),
        ),
    ]
