# Generated by Django 3.1.6 on 2021-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='is_home_page',
            field=models.BooleanField(default=False, verbose_name='Назначить главной страницей'),
        ),
        migrations.AlterField(
            model_name='page',
            name='portfolio',
            field=models.CharField(choices=[('visitka', 'Сайт визитка'), ('coop', 'Корпоративный сайт'), ('shop', 'Интернет-магазин'), ('landing', 'Лэндинг')], default=1, max_length=50, verbose_name='Какую категорию работ выводить'),
        ),
    ]
