# Generated by Django 3.1.6 on 2021-02-23 13:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210223_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_three',
        ),
        migrations.AlterField(
            model_name='page',
            name='content_one',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Для кого подойдет'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_two',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Что получаете при заказе'),
        ),
    ]
