# Generated by Django 3.1.6 on 2021-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210223_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='price_base',
            field=models.CharField(default='10000', max_length=100, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='page',
            name='price_pro',
            field=models.CharField(default='30000', max_length=100, verbose_name='Индивидуальная цена'),
        ),
    ]
