# Generated by Django 3.1.6 on 2021-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210223_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page.html', 'page.html'), ('home.html', 'home.html'), ('rekalama.html', 'reklama.html')], default=1, max_length=50, verbose_name='Использовать шаблон'),
        ),
    ]
