# Generated by Django 3.1.6 on 2021-02-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210224_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page.html', 'page.html'), ('home.html', 'home.html'), ('reklama.html', 'reklama.html'), ('seo.html', 'seo.html')], default=1, max_length=50, verbose_name='Использовать шаблон'),
        ),
    ]
