# Generated by Django 3.1.6 on 2021-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20211102_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page.html', 'page.html'), ('home.html', 'home.html'), ('reklama.html', 'reklama.html'), ('seo.html', 'seo.html'), ('develop.html', 'develop.html'), ('just-text.html', 'just-text.html'), ('bot.html', 'bot.html')], default=1, max_length=50, verbose_name='Использовать шаблон'),
        ),
    ]
