# Generated by Django 3.1.6 on 2021-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, choices=[('visitka', 'Сайт визитка'), ('coop', 'Корпоративный сайт'), ('shop', 'Интернет-магазин'), ('landing', 'Лэндинг')], default=1, max_length=50, verbose_name='Категория сайта'),
        ),
    ]
