# Generated by Django 3.1.6 on 2021-11-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='show_on_home',
            field=models.BooleanField(default=0, verbose_name='Показывать на главной'),
        ),
    ]
