# Generated by Django 3.1.6 on 2021-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_work_show_on_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, choices=[('visitka', 'Многостраничник'), ('shop', 'Интернет-магазин'), ('landing', 'Лэндинг')], default=1, max_length=50, verbose_name='Категория сайта'),
        ),
    ]
